// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChatProto.proto

package com.hoolai.chat.proto;

public final class ChatProto {
  private ChatProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ChatMsgProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int32 mainType = 1;
    boolean hasMainType();
    int getMainType();
    
    // optional int32 subType = 2;
    boolean hasSubType();
    int getSubType();
    
    // optional int32 channelId = 3;
    boolean hasChannelId();
    int getChannelId();
    
    // optional string userId = 4;
    boolean hasUserId();
    String getUserId();
    
    // optional string userName = 5;
    boolean hasUserName();
    String getUserName();
    
    // optional string targetUserId = 6;
    boolean hasTargetUserId();
    String getTargetUserId();
    
    // optional string targetUserName = 7;
    boolean hasTargetUserName();
    String getTargetUserName();
    
    // optional int32 unionId = 8;
    boolean hasUnionId();
    int getUnionId();
    
    // optional string msg = 9;
    boolean hasMsg();
    String getMsg();
  }
  public static final class ChatMsgProto extends
      com.google.protobuf.GeneratedMessage
      implements ChatMsgProtoOrBuilder {
    // Use ChatMsgProto.newBuilder() to construct.
    private ChatMsgProto(Builder builder) {
      super(builder);
    }
    private ChatMsgProto(boolean noInit) {}
    
    private static final ChatMsgProto defaultInstance;
    public static ChatMsgProto getDefaultInstance() {
      return defaultInstance;
    }
    
    public ChatMsgProto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hoolai.chat.proto.ChatProto.internal_static_ChatMsgProto_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hoolai.chat.proto.ChatProto.internal_static_ChatMsgProto_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int32 mainType = 1;
    public static final int MAINTYPE_FIELD_NUMBER = 1;
    private int mainType_;
    public boolean hasMainType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getMainType() {
      return mainType_;
    }
    
    // optional int32 subType = 2;
    public static final int SUBTYPE_FIELD_NUMBER = 2;
    private int subType_;
    public boolean hasSubType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getSubType() {
      return subType_;
    }
    
    // optional int32 channelId = 3;
    public static final int CHANNELID_FIELD_NUMBER = 3;
    private int channelId_;
    public boolean hasChannelId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getChannelId() {
      return channelId_;
    }
    
    // optional string userId = 4;
    public static final int USERID_FIELD_NUMBER = 4;
    private Object userId_;
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getUserId() {
      Object ref = userId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          userId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUserIdBytes() {
      Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string userName = 5;
    public static final int USERNAME_FIELD_NUMBER = 5;
    private Object userName_;
    public boolean hasUserName() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getUserName() {
      Object ref = userName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          userName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUserNameBytes() {
      Object ref = userName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string targetUserId = 6;
    public static final int TARGETUSERID_FIELD_NUMBER = 6;
    private Object targetUserId_;
    public boolean hasTargetUserId() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public String getTargetUserId() {
      Object ref = targetUserId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          targetUserId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTargetUserIdBytes() {
      Object ref = targetUserId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        targetUserId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string targetUserName = 7;
    public static final int TARGETUSERNAME_FIELD_NUMBER = 7;
    private Object targetUserName_;
    public boolean hasTargetUserName() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public String getTargetUserName() {
      Object ref = targetUserName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          targetUserName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTargetUserNameBytes() {
      Object ref = targetUserName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        targetUserName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 unionId = 8;
    public static final int UNIONID_FIELD_NUMBER = 8;
    private int unionId_;
    public boolean hasUnionId() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public int getUnionId() {
      return unionId_;
    }
    
    // optional string msg = 9;
    public static final int MSG_FIELD_NUMBER = 9;
    private Object msg_;
    public boolean hasMsg() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    public String getMsg() {
      Object ref = msg_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          msg_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getMsgBytes() {
      Object ref = msg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      mainType_ = 0;
      subType_ = 0;
      channelId_ = 0;
      userId_ = "";
      userName_ = "";
      targetUserId_ = "";
      targetUserName_ = "";
      unionId_ = 0;
      msg_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, mainType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, subType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, channelId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getUserIdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getUserNameBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getTargetUserIdBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getTargetUserNameBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, unionId_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, getMsgBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, mainType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, subType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, channelId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getUserIdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getUserNameBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getTargetUserIdBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getTargetUserNameBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, unionId_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getMsgBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    @java.lang.Override
    protected Object writeReplace() throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.hoolai.chat.proto.ChatProto.ChatMsgProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.hoolai.chat.proto.ChatProto.ChatMsgProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.hoolai.chat.proto.ChatProto.ChatMsgProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.hoolai.chat.proto.ChatProto.ChatMsgProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.hoolai.chat.proto.ChatProto.ChatMsgProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.hoolai.chat.proto.ChatProto.ChatMsgProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.hoolai.chat.proto.ChatProto.ChatMsgProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.hoolai.chat.proto.ChatProto.ChatMsgProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.hoolai.chat.proto.ChatProto.ChatMsgProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.hoolai.chat.proto.ChatProto.ChatMsgProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hoolai.chat.proto.ChatProto.ChatMsgProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.hoolai.chat.proto.ChatProto.ChatMsgProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hoolai.chat.proto.ChatProto.internal_static_ChatMsgProto_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hoolai.chat.proto.ChatProto.internal_static_ChatMsgProto_fieldAccessorTable;
      }
      
      // Construct using com.hoolai.chat.proto.ChatProto.ChatMsgProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        mainType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        subType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        channelId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        userId_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        userName_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        targetUserId_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        targetUserName_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        unionId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        msg_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hoolai.chat.proto.ChatProto.ChatMsgProto.getDescriptor();
      }
      
      public com.hoolai.chat.proto.ChatProto.ChatMsgProto getDefaultInstanceForType() {
        return com.hoolai.chat.proto.ChatProto.ChatMsgProto.getDefaultInstance();
      }
      
      public com.hoolai.chat.proto.ChatProto.ChatMsgProto build() {
        com.hoolai.chat.proto.ChatProto.ChatMsgProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.hoolai.chat.proto.ChatProto.ChatMsgProto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.hoolai.chat.proto.ChatProto.ChatMsgProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.hoolai.chat.proto.ChatProto.ChatMsgProto buildPartial() {
        com.hoolai.chat.proto.ChatProto.ChatMsgProto result = new com.hoolai.chat.proto.ChatProto.ChatMsgProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.mainType_ = mainType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.subType_ = subType_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.channelId_ = channelId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.userName_ = userName_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.targetUserId_ = targetUserId_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.targetUserName_ = targetUserName_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.unionId_ = unionId_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.msg_ = msg_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hoolai.chat.proto.ChatProto.ChatMsgProto) {
          return mergeFrom((com.hoolai.chat.proto.ChatProto.ChatMsgProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.hoolai.chat.proto.ChatProto.ChatMsgProto other) {
        if (other == com.hoolai.chat.proto.ChatProto.ChatMsgProto.getDefaultInstance()) return this;
        if (other.hasMainType()) {
          setMainType(other.getMainType());
        }
        if (other.hasSubType()) {
          setSubType(other.getSubType());
        }
        if (other.hasChannelId()) {
          setChannelId(other.getChannelId());
        }
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (other.hasUserName()) {
          setUserName(other.getUserName());
        }
        if (other.hasTargetUserId()) {
          setTargetUserId(other.getTargetUserId());
        }
        if (other.hasTargetUserName()) {
          setTargetUserName(other.getTargetUserName());
        }
        if (other.hasUnionId()) {
          setUnionId(other.getUnionId());
        }
        if (other.hasMsg()) {
          setMsg(other.getMsg());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              mainType_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              subType_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              channelId_ = input.readInt32();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              userId_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              userName_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              targetUserId_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              targetUserName_ = input.readBytes();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              unionId_ = input.readInt32();
              break;
            }
            case 74: {
              bitField0_ |= 0x00000100;
              msg_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 mainType = 1;
      private int mainType_ ;
      public boolean hasMainType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getMainType() {
        return mainType_;
      }
      public Builder setMainType(int value) {
        bitField0_ |= 0x00000001;
        mainType_ = value;
        onChanged();
        return this;
      }
      public Builder clearMainType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        mainType_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 subType = 2;
      private int subType_ ;
      public boolean hasSubType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getSubType() {
        return subType_;
      }
      public Builder setSubType(int value) {
        bitField0_ |= 0x00000002;
        subType_ = value;
        onChanged();
        return this;
      }
      public Builder clearSubType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        subType_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 channelId = 3;
      private int channelId_ ;
      public boolean hasChannelId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getChannelId() {
        return channelId_;
      }
      public Builder setChannelId(int value) {
        bitField0_ |= 0x00000004;
        channelId_ = value;
        onChanged();
        return this;
      }
      public Builder clearChannelId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        channelId_ = 0;
        onChanged();
        return this;
      }
      
      // optional string userId = 4;
      private Object userId_ = "";
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getUserId() {
        Object ref = userId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUserId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        userId_ = value;
        onChanged();
        return this;
      }
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      void setUserId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        userId_ = value;
        onChanged();
      }
      
      // optional string userName = 5;
      private Object userName_ = "";
      public boolean hasUserName() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getUserName() {
        Object ref = userName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          userName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUserName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        userName_ = value;
        onChanged();
        return this;
      }
      public Builder clearUserName() {
        bitField0_ = (bitField0_ & ~0x00000010);
        userName_ = getDefaultInstance().getUserName();
        onChanged();
        return this;
      }
      void setUserName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        userName_ = value;
        onChanged();
      }
      
      // optional string targetUserId = 6;
      private Object targetUserId_ = "";
      public boolean hasTargetUserId() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public String getTargetUserId() {
        Object ref = targetUserId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          targetUserId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTargetUserId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        targetUserId_ = value;
        onChanged();
        return this;
      }
      public Builder clearTargetUserId() {
        bitField0_ = (bitField0_ & ~0x00000020);
        targetUserId_ = getDefaultInstance().getTargetUserId();
        onChanged();
        return this;
      }
      void setTargetUserId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000020;
        targetUserId_ = value;
        onChanged();
      }
      
      // optional string targetUserName = 7;
      private Object targetUserName_ = "";
      public boolean hasTargetUserName() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public String getTargetUserName() {
        Object ref = targetUserName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          targetUserName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTargetUserName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        targetUserName_ = value;
        onChanged();
        return this;
      }
      public Builder clearTargetUserName() {
        bitField0_ = (bitField0_ & ~0x00000040);
        targetUserName_ = getDefaultInstance().getTargetUserName();
        onChanged();
        return this;
      }
      void setTargetUserName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000040;
        targetUserName_ = value;
        onChanged();
      }
      
      // optional int32 unionId = 8;
      private int unionId_ ;
      public boolean hasUnionId() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public int getUnionId() {
        return unionId_;
      }
      public Builder setUnionId(int value) {
        bitField0_ |= 0x00000080;
        unionId_ = value;
        onChanged();
        return this;
      }
      public Builder clearUnionId() {
        bitField0_ = (bitField0_ & ~0x00000080);
        unionId_ = 0;
        onChanged();
        return this;
      }
      
      // optional string msg = 9;
      private Object msg_ = "";
      public boolean hasMsg() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public String getMsg() {
        Object ref = msg_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          msg_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setMsg(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        msg_ = value;
        onChanged();
        return this;
      }
      public Builder clearMsg() {
        bitField0_ = (bitField0_ & ~0x00000100);
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      void setMsg(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000100;
        msg_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:ChatMsgProto)
    }
    
    static {
      defaultInstance = new ChatMsgProto(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ChatMsgProto)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ChatMsgProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ChatMsgProto_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017ChatProto.proto\"\262\001\n\014ChatMsgProto\022\020\n\010ma" +
      "inType\030\001 \001(\005\022\017\n\007subType\030\002 \001(\005\022\021\n\tchannel" +
      "Id\030\003 \001(\005\022\016\n\006userId\030\004 \001(\t\022\020\n\010userName\030\005 \001" +
      "(\t\022\024\n\014targetUserId\030\006 \001(\t\022\026\n\016targetUserNa" +
      "me\030\007 \001(\t\022\017\n\007unionId\030\010 \001(\005\022\013\n\003msg\030\t \001(\tB\027" +
      "\n\025com.hoolai.chat.proto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ChatMsgProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ChatMsgProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ChatMsgProto_descriptor,
              new java.lang.String[] { "MainType", "SubType", "ChannelId", "UserId", "UserName", "TargetUserId", "TargetUserName", "UnionId", "Msg", },
              com.hoolai.chat.proto.ChatProto.ChatMsgProto.class,
              com.hoolai.chat.proto.ChatProto.ChatMsgProto.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
